### PR TITLE
Bump version 9.0. Adds windows package

### PR DESCRIPTION
**Pull request by fabratu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fabratu** [comment]
@conda-forge-admin, please rerender

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Comment by lucventurini** [comment]
@fabratu 

`libnetworkit==9.0` is not in conda-forge. The most recent package is `libnetworkit==8.1`. This pipeline will fail until the library is updated ...

**Comment by fabratu** [comment]
> @fabratu
> 
> `libnetworkit==9.0` is not in conda-forge. The most recent package is `libnetworkit==8.1`. This pipeline will fail until the library is updated ...

Sure - currently am pushing updates, trying to solve the Windows/Cython build errors (which don't rely on `libnetworkit`). The other ones are fixed "automatically", since libnetworkit 9.0 will be available on conda-forge index soon. Sry for the spam ;)

**Comment by fabratu** [comment]
@conda-forge-admin, please rerender

**Comment by fabratu** [comment]
@conda-forge-admin, please rerender

**Comment by fabratu** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
